### ISSUE TITLE
FormRadio.php - htmlspecialchars() expects parameter

### ISSUE THREAD

**Issue by Heyula** [XoopsModules25x/modulebuilder#150]
Hi;
Error : TypeError: htmlspecialchars() expects parameter 1 to be string, int given
![0](https://user-images.githubusercontent.com/5504159/152225506-b190d12c-b46c-443f-a03b-37487d9412a8.jpg)
![1](https://user-images.githubusercontent.com/5504159/152225512-cf22b1a5-7b9d-46a7-8b1b-a16841ed6690.jpg)

**Comment by ggoffy** [comment]
see https://github.com/XoopsModules25x/modulebuilder/issues/147

should be fixed

**Comment by liomj** [comment]
Hi ggoffy i downloaded the latest update, it seems the error still exist

**Comment by Heyula** [comment]
After the last update the problem was solved. 
Thanks @ggoffy
